### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/eloquent-hashids.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "mtvs/eloquent-hashids": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by LukasFreyCZ** [comment]
Is this going to be merged soon please?

**Comment by mtvs** [comment]
It doesn't account for another dependency [vinkla/laravel-hashids](https://github.com/vinkla/laravel-hashids). As soon as it is released for Laravel 10, I'll release the compatible version.

**Comment by LukasFreyCZ** [comment]
> It doesn't account for another dependency [vinkla/laravel-hashids](https://github.com/vinkla/laravel-hashids). As soon as it is released for Laravel 10, I'll release the compatible version.

Oh I see. Thanks for the quick reply. :)

**Comment by vonec** [comment]
can you merge this PR

**Comment by mtvs** [comment]
A new release supporting L10 has just been pushed.

**Pull request closed without merging**
